### ISSUE TITLE
[Angel's Petro] Fluid losses when barrelling/unbarrelling

### ISSUE THREAD

**Issue by pjf** [boweiliu/Marathon#2]
Hey Boweiliu! I've spotted a few inconsistencies with some of the fluid barrelling recipes when playing an AngelBob game with Angel's petrochem enabled. All the recipes return the same amount going in as coming out, except for three:

- Lubricant *barrel* (fill: 250, empty: 125)
- Ferric Chloride *canister* (fill: 50, empty: 10)
- Liquid Fuel *canister* (fill: 50, empty: 10)

Many thanks again for a fantastic mod; I'm absolutely loving my marathon game!

~ Paul

**Comment by boweiliu** [comment]
wat. i'll look into it. i know why lubricant is down 50% but unsure what's with the canisters.

**Comment by boweiliu** [comment]
Done in latest ver.

**Comment by pjf** [comment]
Hooray! Thank you so much!
