### ISSUE TITLE
Tags for new releases?

### ISSUE THREAD

**Issue by pjf** [boweiliu/Marathon#5]
Oh hai. It's me again. :)

I might be missing something, but I can't seem to find any git tags for marathomation past than v0.1.0 which is shown on the [releases page](https://github.com/boweiliu/Marathon/releases). While I can mostly reconstruct the release history from the `info.json` file, having tags in git would be fabulous in being able to better track development.

If you've been making tags locally, I don't suppose I could ask you to do a `git push --tags`? Git is notorious for not sharing tags sometimes.

Many thanks again!

~ Paul

**Comment by boweiliu** [comment]
Wasn't too much point when it was just me but i'll start doing this from now on.
